Solution
mate-academy/py-person-class pull request #1020
Opened 2024-02-13 11:27 UTC by AlexTsikhun

Should I add code, that I don't fully understand insted of my bad (but worknig) code?
To get rid of 
`else:
    pass`
I can use:
`people_data.get("wife") and people["wife"] in...`

2024-02-13 11:50 UTC, viktoria-rybenchuk requested changes

2024-02-13 13:11 UTC, AlexTsikhun commented on app/main.py
> +    for people_data in people:
> And after that you can iterate over the people and check if `wife/husband` present and add attribute

but I should use nested loop? (for instances and for people?)

2024-02-13 13:40 UTC, AlexTsikhun commented on app/main.py
> +    for people_data in people:
@viktoria-rybenchuk  , please, help, cause I'm stuck..

2024-02-23 15:40 UTC, Polyakiv-Andrey approved these changes
Good job!

2026-05-17 10:00 UTC, closed without merging