resolved Person class task
mate-academy/py-person-class pull request #1283
Opened 2024-07-09 17:42 UTC by viktor-77

2024-07-09 17:52 UTC, viktoria-rybenchuk requested changes

2024-07-10 11:41 UTC, pavlopro requested changes

2024-07-10 11:41 UTC, pavlopro commented on app/main.py
> +        if "wife" in person and person["wife"] is not None:
Simplify by using:
`if wife_name := person.get("wife"):`

2024-07-10 11:41 UTC, pavlopro commented on app/main.py
> +        elif "husband" in person and person["husband"] is not None:
The same here

2024-07-10 17:06 UTC, pavlopro approved these changes
Good Job!

2025-02-27 12:35 UTC, closed without merging