Solution
mate-academy/py-person-class pull request #1528
Opened 2024-11-08 14:24 UTC by Chukhno-Maksym

2024-11-22 11:15 UTC, petrykivd requested changes

2024-11-22 11:15 UTC, petrykivd commented on app/main.py
> +        person_list.append(Person(peoples["name"], peoples["age"]))
You can also simplify this construction a bit by using list comprehension.

2024-11-22 11:15 UTC, petrykivd commented on app/main.py
> +                    person.husband = spouse
This number of internal IFs is not a good solution. Try to simplify this solution, by removing spouse_name and spouse.

2024-11-22 11:15 UTC, petrykivd commented on app/main.py
> +        person_list.append(Person(peoples["name"], peoples["age"]))
It's not a good idea to add its type to the variable name; it's enough to just name it in plural.

2024-11-26 07:27 UTC, petrykivd requested changes

2024-11-26 07:27 UTC, petrykivd commented on app/main.py
> +            person.husband = Person.people.get(peoples["husband"])
You can simplify this check by using the .get() method. Please use checklist before pushing your solution)

2024-12-02 16:42 UTC, L1nk3rrr reviewed
Well done! Look at my comments, have a minor changes for u

2024-12-02 16:42 UTC, L1nk3rrr commented on app/main.py
> +    for peoples in people:
looks like a bad variable name `peoples` because your dict contains only  data of one person

2024-12-02 16:42 UTC, L1nk3rrr commented on .flake8
> +exclude = venv, tests, .venv
Don't push such changes

2024-12-02 16:44 UTC, L1nk3rrr requested changes
Well done! Look at my comments, have a minor changes for u

2024-12-03 17:18 UTC, L1nk3rrr approved these changes

2025-08-31 08:55 UTC, closed without merging