'3rSolution'
mate-academy/py-person-class pull request #160
Opened 2022-09-18 18:16 UTC by ketstap162

2022-09-19 09:22 UTC, AriohBelskij requested changes

2022-09-19 09:22 UTC, AriohBelskij commented on app/main.py
> +    def __init__(self, name, age):
add type annotation!

2022-09-19 10:15 UTC, AriohBelskij approved these changes
good.

2022-09-20 15:01 UTC, Y-Havryliv requested changes

2022-09-20 17:46 UTC, closed without merging