Solution
mate-academy/py-person-class pull request #1611
Opened 2024-12-03 21:15 UTC by shretsker

2024-12-03 22:54 UTC, TretiakHelen approved these changes

2024-12-03 22:55 UTC, mateacademy-ai-mentor approved these changes
Great job on implementing the `Person` class and the `create_person_list` function! 🎉 While there are a few minor improvements suggested, such as using `dict.get()` for cleaner code and reducing nested `if` statements, these do not impact the core functionality. Keep up the good work, and consider these suggestions for future enhancements! 😊

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-12-03 22:55 UTC, mateacademy-ai-mentor commented on app/main.py
>      pass
The `pass` statement here is unnecessary and can be removed since the function implementation follows immediately after.

2024-12-03 22:55 UTC, mateacademy-ai-mentor commented on app/main.py
> +                    if person_dict["wife"] is not None:
Instead of checking if 'wife' is in `person_dict` and then checking if it's not `None`, you can simplify this using `person_dict.get('wife')` to avoid potential `KeyError` and make the code cleaner as per the checklist.

2024-12-03 22:55 UTC, mateacademy-ai-mentor commented on app/main.py
> +                    if person_dict["husband"] is not None:
Similarly, use `person_dict.get('husband')` to simplify the code and avoid potential `KeyError` as recommended in the checklist.

2024-12-03 22:55 UTC, mateacademy-ai-mentor commented on app/main.py
> +                    if person_dict["husband"] is not None:
Consider combining the nested `if` statements using logical operators to reduce nesting, as suggested in the checklist. For example, `if person_dict.get('wife'):` and `if person_dict.get('husband'):`.

2024-12-04 08:26 UTC, petrykivd requested changes
Follow Buddy's comments and fix them all.

2024-12-04 08:26 UTC, petrykivd commented on app/main.py
> +                    if person_dict["wife"] is not None:
Nested "for loop" it's not good solution. Try to simplify your solution.

2024-12-05 14:53 UTC, petrykivd requested changes

2024-12-05 14:53 UTC, petrykivd commented on app/main.py
> +
We need to improve the code style and naming.
You should not specify what type of variable it is in the variable name.

 That's a good option:
persons = [
        Person(person_data["name"], person_data["age"])
        for persond_data in people
        ]

2024-12-05 14:53 UTC, petrykivd commented on app/main.py
> +            person.husband = Person.people.get(person_dict["husband"])
Simplify your condition, just use .get() method for it.

2024-12-05 14:53 UTC, petrykivd commented on app/main.py
> +#     return person_list
Remove comments

2024-12-09 17:12 UTC, L1nk3rrr requested changes
If you have any troubles with automated tests, write in the QnA chat and ask mentors, don't try to avoid by `if-else`.
You are almost done! Some minor improvements are needed

2024-12-09 17:12 UTC, L1nk3rrr commented on app/main.py
> +            # should not have attribute wife"
Okey, that now a mistake from test side :)

Your code must handle all variations that tests runs. You can add check like `if "wife" in person_dict` and on it `if` check a value if it exist by .get() method for example

2024-12-09 17:12 UTC, L1nk3rrr commented on app/main.py
> +
Okey, you did it, look for a styling side, now it not using best practices, re-check checklists

2025-10-05 20:41 UTC, closed without merging