Solution
mate-academy/py-person-class pull request #260
Opened 2022-11-09 17:31 UTC by Isles22

2022-11-10 08:31 UTC, DmytroSvirsa requested changes

2022-11-10 08:31 UTC, DmytroSvirsa commented on app/main.py
> +                        human.husband = human_family
that`s will work but slowly, let`s make it less nested, I mean not nested at all

2022-11-10 08:31 UTC, DmytroSvirsa commented on app/main.py
> +    arr = []
not self-explaining variable name

2022-11-11 18:45 UTC, Isles22 commented
Solution fixed

чт, 10 нояб. 2022 г. в 10:31, Dmytro Svirsa ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/main.py
> <https://github.com/mate-academy/py-person-class/pull/260#discussion_r1018786337>
> :
>
> > +    for obj in people:
> +        for human in arr:
> +            if obj["name"] == human.name:
> +                for human_family in arr:
> +                    if obj.get("wife") == human_family.name:
> +                        human.wife = human_family
> +                    if obj.get("husband") == human_family.name:
> +                        human.husband = human_family
>
> thats will work but slowly, lets make it less nested, I mean not nested
> at all
> ------------------------------
>
> In app/main.py
> <https://github.com/mate-academy/py-person-class/pull/260#discussion_r1018786834>
> :
>
> >
>
>  def create_person_list(people: list) -> list:
> -    # write your code here
> -    pass
> +
> +    arr = []
>
> not self-explaining variable name
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/py-person-class/pull/260#pullrequestreview-1175267359>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2K6XNYCAOAH6J3CMN25M4LWHSXF3ANCNFSM6AAAAAAR3VTW44>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-22 10:36 UTC, OleksandrPozden approved these changes
well done!

2022-11-26 08:36 UTC, closed without merging