My_Solution
mate-academy/py-person-class pull request #311
Opened 2022-12-23 09:24 UTC by neagarr

@Abnormaltype 
I would like to ask: why "person_list[i].wife = pair_person" and "person_list[i].husband = pair_person" have the warning "Unresolved attribute reference 'wife' for class 'Person'" in Pycharm?  
According to the course materials, we can complete adding new instance attributes by using instance.attribute_name = value

2022-12-23 09:42 UTC, Abnormaltype reviewed
because you don't have annotation for these list)

2022-12-23 20:06 UTC, neagarr commented
So, where I should make the annotation? Should I?

2022-12-24 11:18 UTC, Abnormaltype requested changes

2022-12-24 11:18 UTC, Abnormaltype commented on app/main.py
> +    person_list = []
```suggestion
    person_list: list[Person] = []
```

2022-12-25 06:55 UTC, neagarr commented
I added list[Person], but nothing changed. Now :
1. "person_list: list[Person] = [] has the warning "Builtin 'list' cannot be parameterized directly"
2. "person_list[i].wife = pair_person" and "person_list[i].husband = pair_person" have the warning "Unresolved attribute reference 'wife' for class 'Person'"

But everything works)

2022-12-27 15:01 UTC, IvanRamyk approved these changes

2023-02-19 21:09 UTC, closed without merging