Solution
mate-academy/py-person-class pull request #34
Opened 2022-05-16 13:09 UTC by rotsen18

2022-05-18 09:24 UTC, Magus6784 approved these changes
Great job. Really readable code
A little confused at the beginning of the number of lines, but readability > size

2022-05-18 12:42 UTC, TPolina requested changes

2022-05-18 12:42 UTC, TPolina commented on app/main.py
> +        Person(individual['name'], individual['age'])
use double quotes everywhere

2022-05-19 07:47 UTC, TPolina approved these changes
Good job!

2023-05-21 09:58 UTC, closed without merging