solution
mate-academy/py-person-class pull request #417
Opened 2023-02-10 15:48 UTC by tarasavage

2023-02-11 09:47 UTC, Grayder0152 approved these changes

2023-02-11 09:47 UTC, Grayder0152 commented on app/main.py
> +        if "wife" in person.keys() and person["wife"]:
Instead of this condition you can use `person.get('wife') is not None`

2023-02-11 09:47 UTC, Grayder0152 commented on app/main.py
> +        if "wife" in person.keys() and person["wife"]:
Apart from this, you can use `:=` operator, but it is not necessary

2023-02-11 09:47 UTC, Grayder0152 commented on app/main.py
> +        elif "husband" in person.keys() and person["husband"]:
The same as above

2023-02-11 09:47 UTC, Grayder0152 commented on app/main.py
> +            wife = Person(person["name"], person["age"])
You need to get person from `people` not create

2023-02-11 09:48 UTC, Grayder0152 requested changes

2023-02-11 09:48 UTC, Grayder0152 commented on app/main.py
> +            husband = Person(person["name"], person["age"])
The same as above

2023-02-18 10:49 UTC, Bohdan-Salamakha commented on app/main.py
> +def create_person_list(people: list) -> list[Person]:
add additional typehint for list inner objects

2023-02-18 10:50 UTC, Bohdan-Salamakha commented on app/main.py
> +        Person(person["name"], person["age"])
use get method instead of parenthesis everywhere to avoid KeyError

2023-02-18 10:50 UTC, Bohdan-Salamakha requested changes
v1

2023-04-03 15:46 UTC, closed without merging