Solution
mate-academy/py-person-class pull request #457
Opened 2023-03-09 18:28 UTC by denysbelei9

2023-04-01 18:09 UTC, Bohdan-Salamakha requested changes
fix flake8

2023-04-04 18:51 UTC, denysbelei9 reviewed
it is solution with flak8 and pytest

2023-04-04 18:51 UTC, denysbelei9 commented on app/main.py
>          self.__class__.people[name] = self
цей кусок коду працює

2023-04-04 18:51 UTC, denysbelei9 commented on app/main.py
> +    return person_list
і цей, не розумію чому воно загрузило частинами, виходить що я воно загружує останнє збереження а останній скомрільований код

2023-04-08 09:41 UTC, closed without merging