solution
mate-academy/py-person-class pull request #485
Opened 2023-03-31 09:58 UTC by alim2709

2023-03-31 12:21 UTC, ArsenPidhoretskyi requested changes

2023-03-31 12:21 UTC, ArsenPidhoretskyi commented on app/main.py
> +        self.__class__.people[name] = self
```suggestion
        self.people[name] = self
```
It is not needed. You can just use self.people

2023-03-31 12:21 UTC, ArsenPidhoretskyi commented on app/main.py
> +        result += {Person(person.get("name"), person.get("age"))}
Use list comprehension

2023-03-31 12:21 UTC, ArsenPidhoretskyi commented on app/main.py
> +    for i, person in enumerate(people):
Why you need i

2023-03-31 12:21 UTC, ArsenPidhoretskyi commented on app/main.py
> +            result[i].wife = Person.people.get(person["wife"])
Objects are mutable. Then if you change it inside
Person.people it will affect result also

2023-03-31 12:21 UTC, ArsenPidhoretskyi commented on app/main.py
> +        if "wife" in person and person.get("wife") is not None:
```suggestion
        if person.get("wife") is not None:
```
The same with husband

2023-03-31 17:57 UTC, Bohdan-Salamakha commented on app/main.py
> +        i += 1
use for i in range(len(people)):
to avoid i = 0, i+= 1

u don't need to use C-like counters in Python

2023-03-31 17:57 UTC, Bohdan-Salamakha requested changes
v1

2023-04-01 08:46 UTC, Bohdan-Salamakha approved these changes

2023-04-01 20:51 UTC, closed without merging