py-person-class
mate-academy/py-person-class pull request #511
Opened 2023-04-30 14:05 UTC by muriakula

2023-04-30 14:33 UTC, Bohdan-Salamakha commented on app/main.py
> +        print(person)
print new_person in a previous loop

2023-04-30 14:34 UTC, Bohdan-Salamakha commented on app/main.py
> +        Person(name, age)
find result using list comprehension and use persons from it

2023-04-30 14:34 UTC, Bohdan-Salamakha requested changes
v1

2023-04-30 17:14 UTC, Bohdan-Salamakha commented on app/main.py
> +    return list(Person.people.values())
```suggestion
    person_list = [Person(person["name"], person["age"]) for person in people]
    for person in people:
        if person.get("husband"):
            wife = Person.people[person["name"]]
            husband = Person.people[person["husband"]]
            wife.husband = husband
            husband.wife = wife
    return person_list
```

2023-04-30 17:14 UTC, Bohdan-Salamakha requested changes
v2

2023-05-01 15:11 UTC, olena-hul approved these changes

2023-05-01 15:11 UTC, olena-hul commented
Good job!

2024-10-29 10:12 UTC, closed without merging