Solution
mate-academy/py-person-class pull request #635
Opened 2023-07-23 12:13 UTC by AlexPelevin99

2023-07-23 17:43 UTC, pavlejviki requested changes
All checks should have been passed.

2023-07-23 18:25 UTC, AlexPelevin99 commented
one checks not passed because test has error
![image](https://github.com/mate-academy/py-person-class/assets/139041359/cc48d3ed-7cbf-4175-a5ab-caf92f71e52e)

2023-07-24 07:42 UTC, Dimosphen1 requested changes
Resolve issues raised by `flake8`.

2023-07-24 07:42 UTC, Dimosphen1 commented on app/main.py
> +    for p in people:
Such variable name as `p` is not allowed as stated by `flake8`. Replace it with a more descriptive one, e.g. `person`.

2023-07-24 07:42 UTC, Dimosphen1 commented on app/main.py
> +    for p in people:
Do not use single-letter variable names here.

2023-07-24 07:42 UTC, Dimosphen1 commented on app/main.py
> +        return cls.people[name]
It would be better to use `.get()` here thus making code less error-prone.

2023-07-24 08:13 UTC, Dimosphen1 requested changes
Several changes were requested, check tests before adding changes.

2023-07-24 08:13 UTC, Dimosphen1 commented on app/main.py
> +from __future__ import annotations
Do not use this import here, it breaks the tests.

2023-07-24 08:13 UTC, Dimosphen1 commented on app/main.py
> +        return cls.people.get(name)
There is no need for this classmethod, you should get value from `people` attribute from the `Person` class directly.

2023-07-30 09:35 UTC, closed without merging