Solution
mate-academy/py-person-class pull request #697
Opened 2023-08-21 19:13 UTC by Daniil-Pankieiev

2023-09-26 13:34 UTC, LiudmylaKulinchenko requested changes

2023-09-26 13:34 UTC, LiudmylaKulinchenko commented on app/main.py
> +        person = Person(name, age)
Use list comprehentsion to create list of Person instances

2023-09-26 13:34 UTC, LiudmylaKulinchenko commented on app/main.py
> +        if "wife" in person_info and person_info["wife"] is not None:
Use just dict.get() method in the condition, instead of this long one

2023-09-27 11:57 UTC, Familenko approved these changes

2024-05-15 11:12 UTC, closed without merging